version: "2.4"
services:
  nginx:
    image: nginx:1.21.1-alpine
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/templates
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - app
  app:
    image: REPOSITORY_URL:CI_COMMIT_SHA
    env_file:
      - .env
    ports:
      - "${PORT}:8080"
      - "${TLS_PORT}:8081"
      - "${NOTIFICATION_PORT}:8085"
      - "${GEOLOCATION_PORT}:8086"
    tty: true
    command: bash -c "npm run migrate && npm run start"
    restart: always
    networks:
      - default
    depends_on:
      - redis
  redis:
    image: bitnami/redis:6.2
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - default
networks:
  default:
